site_name: DiscOps User Guide
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
copyright: Copyright &copy; 2024 - Ernst & Young
plugins:
  - offline
  - mkdocs-nav-weight:
      section_renamed: false
      index_weight: -10
      warning: true
      reverse: false
      headless_included: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
