name: MkDocs Build

on:
  push:
    paths:
      - 'userGuide/**'  # Trigger on push to files under userGuide/docs directory
  workflow_dispatch:
    inputs:
      trigger:
        description: 'trigger manually'
        required: false
        default: 'manual'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python and dependencies
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install MkDocs and Material theme
      run: |
        pip install mkdocs mkdocs-material

    - name: Build MkDocs
      run: mkdocs build -f userGuide/mkdocs.yml -d ../site
      
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Build MkDocs documentation"
        git push
